print('Desafio 04 - Monstransdo as Informações!')
algo = input('Digite algo de sua escolha: ')
print(type(algo))
print('É composto letras? ', algo.isalpha())
print('É composto por números? ', algo.isnumeric())
print('Está tudo minúsculo? ', algo.islower())
print('Está tudo maiúsculo? ',algo.isupper())